### ISSUE TITLE
Request to fix something 

### ISSUE THREAD

**Issue by jcheema468** [relisiuol/RemoveThatLine2#1]
![2E03B1C7-2427-496B-B27B-1A2D1F53FEA8](https://user-images.githubusercontent.com/34690992/70067105-cbf14d80-1613-11ea-88b0-22cce3c34908.png)
Hey bro ! Thank you so much for making this tweak i love this tweak but I guess you have forgotten something!! After installing i have noticed that this tweak removes upper line in apps but not lower line can you please fix it!!! 🤩😊☺️😻🙏🏻

**Comment by relisiuol** [comment]
Fixed in https://github.com/relisiuol/RemoveThatLine2/commit/e3fc863f35dc6adc8d6c81ab96c09ccbc8c65ca5
